### ISSUE TITLE
Unable to detect proper architechure

### ISSUE THREAD

**Issue by omunni** [stevenmirabito/asterisk-picotts#1]
I tried the the script and it gives me download errors. I modified the script by deleting the " # Check architecture" section and directly inputting the variable i386 (in my case) where needed. Afterwards, everything worked as expected. There where a couple of other errors when moving files into place (file already exist) but I guess it had to do with the fact that I ran the script twice. Nevertheless, the TTS installed properly after the changes made and worked fine.

**Comment by stevenmirabito** [comment]
I was incorrectly assigning variables in the script - sorry!

Fixed with https://github.com/stevenmirabito/asterisk-picotts/commit/d42d2ab606b276bfe72cd035c1c96fa80afa2d1b
