### ISSUE TITLE
data.tar.xz missing for CentOS install

### ISSUE THREAD

**Issue by wardmundy** [stevenmirabito/asterisk-picotts#2]
wget http://mirrors.kernel.org/ubuntu/pool/multiverse/s/svox/libttspico-utils_1.0%2bgit20130326-3_${pkgarch}.deb
ar x libttspico-utils_1.0+git20130326-3_${pkg-arch}.deb data.tar.xz

**Comment by stevenmirabito** [comment]
Fixed with https://github.com/stevenmirabito/asterisk-picotts/commit/94fa20159a37b7d473d885e2b0b5121a22bfec16
